spring:
  application:
    name: lyhm-ai-code
#??knife4j???
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lyhm.lyhmaicode.controller

knife4j:
  enable: true
  setting:
    language: zh_cn